In [2]:
import numpy 
import pandas
import os 
import sys 


data_train = pandas.read_csv(r'SalvageBidDataTrain.csv')
data_train

,Vehicle_ID,Pre_Accident_Value,Cost_of_repair,odometer,engine_displacement,Damage_Type,make_nm,model_nm,fuel_type,Age,Sale_Price
0,2560,11781.000000,8576.9,6576,998,Front End,Citroen,C1,Petrol,0,5100
1,1150,4165.000000,4450.9,182641,1598,Front End,Opel,Astra,Petrol,12,1850
2,1125,6307.000000,3951.8,58648,998,Front End,Opel,Corsa,Petrol,6,1700
3,2006,5600.021000,6678.6,106851,1198,Front End,Volkswagen,Polo V,Petrol,8,2800
4,298,3904.257778,9500.0,115803,1896,Side,Volkswagen,Touran,Diesel,13,2600
...,...,...,...,...,...,...,...,...,...,...,...
2393,1940,8600.011000,21008.4,55400,1598,Front End,Citroen,Berlingo Kombi,Petrol,6,2550
2394,3009,13209.000000,12015.1,32215,999,Front End,Skoda,Fabia Combi,Petrol,3,3650
2395,3016,4403.000000,5297.3,58181,1242,Front End,FIAT,Panda,Petrol,9,1700
2396,2292,7400.015000,6841.1,55185,1198,Front End,Volkswagen,Polo V,Petrol,8,3050
2397,1248,8151.500000,9430.4,82356,1390,Side,Seat,Ibiza,Petrol,6,1650

In [3]:
data_test = pandas.read_csv(r'SalvageBidTest.csv')
data_test

,Vehicle_ID,Pre_Accident_Value,Cost_of_repair,odometer,engine_displacement,Damage_Type,make_nm,model_nm,fuel_type,Age
0,2949,3332.000,2554.8,50397,998,Front End,Peugeot,107,Petrol,12
1,885,10250.065,17000.0,177016,2987,Front End,Jeep,Grand Cherokee,Diesel,11
2,135,3927.000,5420.2,249189,1686,Rear End,Opel,Astra,Diesel,9
3,1351,20468.000,22881.8,66194,1591,Side,Kia,Cee'd,Petrol,3
4,2823,3451.000,3986.3,96269,1299,Front End,Ford,Fiesta,Petrol,11
...,...,...,...,...,...,...,...,...,...,...
698,461,20882.300,19820.3,13016,1698,Side,Volkswagen,Golf VII Variant,Diesel,1
699,1445,6069.000,7374.0,125536,1396,Side,Hyundai,i30,Petrol,8
700,1741,4249.966,10900.0,50171,1388,Side,Ford,Focus,Petrol,11
701,2286,6700.000,16570.0,89397,1388,Front End,Ford,B-Max,Petrol,2
702,1016,8092.000,10000.0,109211,1596,Front End,Ford,Focus,Petrol,6

In [4]:
data_train.describe()

,Vehicle_ID,Pre_Accident_Value,Cost_of_repair,odometer,engine_displacement,Age,Sale_Price
count,2398.000000,2398.000000,2398.000000,2398.000000,2398.000000,2398.000000,2398.000000
mean,1549.684737,8629.943378,9173.597164,101867.237281,1558.057548,7.512093,3340.679733
std,891.275982,5627.630051,5923.377102,64452.125426,441.387914,3.885037,2542.178340
min,2.000000,924.987000,482.600000,155.000000,698.000000,0.000000,325.000000
25%,779.250000,4799.984000,5298.500000,51846.000000,1242.000000,5.000000,1700.000000
50%,1548.500000,6902.000000,7728.100000,95925.000000,1491.500000,8.000000,2650.000000
75%,2321.500000,10710.000000,11319.700000,142966.000000,1798.000000,10.000000,4100.000000
max,3101.000000,42249.998000,58823.500000,369474.000000,5462.000000,20.000000,19100.000000

In [5]:
data_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Vehicle_ID           2398 non-null   int64
 1   Pre_Accident_Value   2398 non-null   float64
 2   Cost_of_repair       2398 non-null   float64
 3   odometer             2398 non-null   int64
 4   engine_displacement  2398 non-null   int64
 5   Damage_Type          2398 non-null   object
 6   make_nm              2398 non-null   object
 7   model_nm             2398 non-null   object
 8   fuel_type            2398 non-null   object
 9   Age                  2398 non-null   int64
 10  Sale_Price           2398 non-null   int64
dtypes: float64(2), int64(5), object(4)
memory usage: 206.2+ KB

In [46]:
import xgboost 
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler

x = data_train.loc[:, data_train.columns != 'Sale_Price']
x = OneHotEncoder().fit_transform(x)
x_dmatrix = xgboost.DMatrix(x)
y = data_train['Sale_Price']
y_dmatrix = xgboost.DMatrix(y)
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1)
holdout = OneHotEncoder().fit_transform(data_test)

In [54]:
x = data_train.loc[:, data_train.columns != 'Sale_Price']
x = x.select_dtypes(include = numpy.number)
#x = OneHotEncoder().fit_transform(x)
x_dmatrix = xgboost.DMatrix(x)
y = data_train['Sale_Price']
y_dmatrix = xgboost.DMatrix(y)
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.1)
holdout = data_test.select_dtypes(include = numpy.number)

In [55]:
print(holdout)

     Vehicle_ID  Pre_Accident_Value  Cost_of_repair  odometer  \
0          2949            3332.000          2554.8     50397
1           885           10250.065         17000.0    177016
2           135            3927.000          5420.2    249189
3          1351           20468.000         22881.8     66194
4          2823            3451.000          3986.3     96269
..          ...                 ...             ...       ...
698         461           20882.300         19820.3     13016
699        1445            6069.000          7374.0    125536
700        1741            4249.966         10900.0     50171
701        2286            6700.000         16570.0     89397
702        1016            8092.000         10000.0    109211

     engine_displacement  Age
0                    998   12
1                   2987   11
2                   1686    9
3                   1591    3
4                   1299   11
..                   ...  ...
698                 1698    1
699                 1396    8
700                 1388   11
701                 1388    2
702                 1596    6

[703 rows x 6 columns]

In [56]:
xgb = xgboost.XGBRegressor(objective = 'reg:squarederror')
xgb.fit(x, y)
pred = xgb.predict(holdout)

In [58]:
pred

array([ 1057.9633 ,  4200.0273 ,  1657.103  ,  6649.5347 ,  1060.9719 ,
        2726.6514 ,  1857.8252 ,  1755.3256 ,  1866.3588 ,  6105.275  ,
        1391.3336 ,  2510.3425 ,  2420.1404 ,  2099.8242 ,  1768.5193 ,
        7114.285  ,  4320.1855 ,  1391.1807 ,  1699.9469 ,  3394.3997 ,
        2975.125  ,  5264.4663 ,  6350.4634 ,  6586.898  , 10644.258  ,
        2177.387  ,  5818.3384 ,  5310.481  ,  3072.9656 ,  2291.9573 ,
       15514.065  ,  1323.0135 ,  2203.065  , 10057.386  ,  1255.3356 ,
        2171.8015 ,  2303.6982 ,  1166.1256 ,  3318.4502 ,  6784.4116 ,
        1216.2386 ,  2205.7632 ,  8739.585  ,  6861.9634 ,  2713.0593 ,
        2466.8486 ,  4928.267  ,  3736.3403 ,  5067.1533 ,  1746.4489 ,
        1789.3242 ,  1881.8213 ,  2095.2637 ,  4242.5264 ,  7434.5693 ,
        3681.3828 ,  1689.8767 ,  1556.5608 ,  3851.7397 ,  1743.5116 ,
        5280.573  ,  3075.9792 ,  2127.765  ,   933.06995,  3392.1572 ,
        2411.3774 ,  1840.7854 ,  3690.156  ,  1238.9329 ,  2531.409  ,
        1555.6481 ,  3243.979  ,  2574.499  ,  1345.7625 ,  2539.6794 ,
        1843.4552 ,  3935.1917 ,  1370.2443 ,  7806.273  ,  3672.8806 ,
         869.0557 ,  4812.2344 ,  1140.7684 ,  1164.3401 ,  2104.8872 ,
        2630.5957 ,  1448.6893 ,  1868.3721 ,  6475.1777 ,  3796.0645 ,
        2241.4006 ,  1500.1285 ,  3547.7295 ,  1120.3204 ,  1629.1127 ,
        2146.9941 ,  1788.6334 ,  1846.481  ,  2938.7468 ,  2064.695  ,
        2247.292  ,  8553.062  ,  8838.073  ,  9118.3955 ,   640.4556 ,
        2367.5151 ,  4311.1733 ,  1330.8197 ,  2276.5662 ,  1415.98   ,
        1964.829  ,  9694.186  ,  2894.2585 ,  5383.6367 ,  1643.3811 ,
        2563.6648 ,  1943.057  ,  3609.1853 ,   982.77124,  2904.6711 ,
        2001.0574 ,  1702.5342 ,  1183.7311 ,  3870.2136 ,  1909.0281 ,
        3349.0215 ,  3451.4915 ,  1575.863  ,  1901.0115 ,  2589.1846 ,
        5715.196  ,  2232.1567 ,  3170.5044 ,  2454.3403 ,  1427.9298 ,
        3038.142  ,  2690.427  ,  2273.17   ,  2471.4763 ,   588.8726 ,
        6725.033  ,  1742.9893 ,  1993.4988 ,  5925.3887 ,  3660.712  ,
        2296.8782 ,  1037.0575 ,  2373.8855 ,  6706.569  ,  1326.908  ,
        3394.9585 ,  1445.6287 ,  2691.6338 ,  4595.6587 ,  3858.372  ,
        2507.712  ,  1010.7815 ,  1150.9258 , 16858.562  ,  7332.2144 ,
        2014.0044 ,  2006.1953 ,  2922.571  ,  3250.375  ,  2583.0962 ,
        9676.458  ,  4855.696  ,  2641.7793 , 10295.436  ,  2673.4653 ,
        2866.8264 ,  1054.7225 ,  1005.8283 ,  4270.9023 ,  2816.357  ,
        1112.2354 ,  4190.2485 ,  1019.62396,  3268.498  ,  1715.0624 ,
        2472.7778 ,  7608.9873 ,  1847.6992 ,  2551.8862 ,  4806.8706 ,
        1281.6482 ,  1414.2695 ,  1960.7832 ,  5204.4434 ,  1640.6368 ,
        1997.0057 ,  2354.01   ,  2060.6052 ,  2025.3173 ,  9430.881  ,
        1494.4028 ,  2086.929  ,  1847.1509 ,   940.56805,  1477.7793 ,
        1365.92   ,  2494.9155 ,   964.5032 ,  2819.382  ,  4473.359  ,
        2251.5007 ,  2246.1191 ,  2707.644  ,  1299.9016 , 10594.741  ,
        2486.2417 ,  9570.661  ,  1269.3893 ,  3087.4104 ,  3486.076  ,
        2151.1145 ,  4286.942  ,  5137.1577 ,   714.3491 ,  2531.3872 ,
        1153.8444 ,  2255.6848 ,  1262.7142 ,  2891.6326 ,  2509.7764 ,
         644.05585,  3733.4993 ,  3019.1519 ,  1690.6077 ,  6269.474  ,
        3782.3938 ,  2000.9542 ,  2336.6067 ,  4495.7407 ,  1714.5582 ,
        7398.299  ,  7524.84   ,  9180.764  ,  1697.7687 ,  4159.891  ,
        2014.9225 ,  4321.299  ,  2912.2417 ,  1973.1179 ,  9526.259  ,
        6037.037  ,  1063.5776 ,  4440.584  ,  7062.0176 ,  3006.3445 ,
        1055.8965 ,  1569.451  ,  2463.3416 ,  2286.1287 ,  7746.6123 ,
        3485.113  ,  1539.6082 ,  7049.609  ,  2079.1426 ,  1485.251  ,
        4038.5999 ,  4203.124  ,  3045.1594 ,  6220.4263 ,  8428.815  ,
        1368.878  ,  1291.4491 ,  1550.8928 ,  1144.3175 ,  2376.1323 ,
        5482.5664 ,  1014.03925,  2410.0183 ,  2427.3333 ,  2490.2634 ,
        1445.176  ,  1360.9045 ,  1327.9635 ,  3990.213  ,  2971.4114 ,
        6455.3574 ,  5441.559  ,  1723.2805 ,  5137.726  ,  8084.5615 ,
        2089.4185 ,  2982.5774 , 13573.59   ,  3536.4624 ,  1777.7198 ,
        3122.5835 ,  3152.8533 ,  1390.8154 ,  2885.1233 ,  2045.384  ,
        1103.0105 ,  7009.6274 ,  1987.3588 ,  2490.4158 ,  8189.3687 ,
        1841.4083 ,  1445.4741 ,  2115.6655 ,  2285.6985 ,  2176.183  ,
       10051.64   ,  1875.8788 ,  1983.4355 ,  4368.7607 ,  2128.8955 ,
        1899.2599 ,  1880.0181 ,  1764.1427 ,  2803.377  ,  2880.1245 ,
        2990.7554 ,  1624.9319 ,  4816.892  ,  2439.5676 ,  2331.514  ,
        1884.5573 ,  6215.857  ,  3190.8438 ,  3816.546  ,  2372.6628 ,
        6276.0684 ,  3692.6306 ,  2976.4133 ,  2790.2876 ,  1060.9456 ,
        8437.482  ,  1528.9896 ,  1390.2391 ,  6438.71   ,  3069.519  ,
        1725.6339 ,  4916.6777 ,  8261.403  ,  2597.9465 ,  1680.7378 ,
        2233.3894 ,  1454.9618 ,  1573.564  ,  2299.2869 ,  2052.538  ,
        2607.921  ,  3103.7446 ,  4635.199  ,  4340.0386 ,  3627.5374 ,
        2070.849  ,  1928.9795 ,  5281.975  ,  2449.635  ,  3233.85   ,
        3784.6184 ,  1868.5736 ,  2241.2446 ,  1548.2406 ,  3413.6284 ,
        4040.2942 ,  1135.4882 ,  2325.117  ,  3814.1604 ,  1966.3782 ,
        2616.1614 ,  2121.0325 ,  2386.3545 ,  2431.6174 ,  5516.938  ,
        4131.5547 ,  3740.832  ,  2679.3826 ,  3006.4119 ,  5431.292  ,
        1665.5643 ,  6491.024  ,  1061.7166 ,  1952.202  ,  7096.5776 ,
        1111.3007 ,  3105.6677 ,   976.2255 ,  3377.3257 ,  1804.3036 ,
        4195.3574 ,  1654.7986 ,  3400.5884 ,  1864.6404 ,  1818.6108 ,
        3763.417  ,  3097.4185 ,  3813.605  ,  4099.092  ,  3299.1196 ,
        3874.4832 ,  1908.1143 ,  2439.0535 ,  1211.4233 ,  4115.0747 ,
        1540.0568 ,  2164.7063 ,  2983.4485 ,  2747.095  ,  3929.7505 ,
        2015.0818 ,  5347.4717 ,  4380.2163 ,  1517.2063 ,  1774.9496 ,
        3211.4634 ,  6326.126  ,  9298.104  ,  2784.367  ,  2120.8774 ,
        3439.3398 ,  6975.9185 ,  2729.8748 ,  4626.7876 ,  1896.1935 ,
        3638.454  ,  1039.7032 ,  1536.4794 ,  1343.4841 ,  8650.517  ,
        1870.5096 ,  3247.8308 ,  1305.9421 ,  2145.628  ,  3955.418  ,
        3726.8096 ,  6547.307  ,  3620.9714 ,  2192.9612 ,  3696.8848 ,
        1924.0001 ,  8250.676  ,  1339.8077 ,  7541.2793 ,  2047.9888 ,
        6547.7    ,  1946.3677 ,  2689.278  ,  1408.1288 ,  1733.9512 ,
         981.0998 ,  2971.7268 ,  2701.5305 ,  2008.655  ,  2529.4758 ,
        3837.1223 ,  9662.781  ,  1269.5911 ,  1582.1758 ,  2397.1274 ,
        6301.591  ,  2000.3386 ,  1959.8656 ,  1650.4795 ,   938.60126,
        3988.2395 ,  1612.0206 ,  1940.1908 ,  4311.0454 ,   962.4888 ,
        2344.185  ,  2897.4038 ,  1482.8888 ,  5138.0654 ,  4688.244  ,
        2592.7065 ,  3077.4792 ,  4740.9263 ,  2727.5435 ,  1910.9666 ,
        1967.2551 ,  1653.0188 ,  1598.8033 ,  3867.5862 ,  7332.6543 ,
        4096.076  ,  3573.3174 ,  2475.2178 ,  1712.7175 ,  2059.991  ,
        1447.2555 ,  1854.5458 ,  3276.2808 ,  3226.934  ,  2120.79   ,
        1026.1456 ,  1429.9869 ,  2310.266  ,  3303.387  ,  1579.3413 ,
        2736.4907 ,  6991.3403 ,  1177.4862 ,  2109.8896 ,  1946.6561 ,
        1406.4373 ,  2077.553  ,  1672.7817 ,  1681.8442 ,  2293.8977 ,
        2210.7114 ,  2014.604  ,  2979.0251 ,  1395.5541 ,  7932.6943 ,
         933.88336,  1549.8568 ,  1933.1637 ,  1493.3566 ,  1546.4003 ,
       13165.929  ,  1908.5071 ,  3718.498  ,  1844.7268 ,  7334.5815 ,
        1686.0498 ,  2851.4316 ,   501.0115 ,  4294.1216 ,  6674.8877 ,
        1607.1727 ,  2556.5122 ,  1070.5906 ,  2605.0288 ,  4822.9956 ,
        2599.4155 , 11875.894  ,  1791.2014 ,  7016.505  ,  1134.292  ,
        1121.3041 ,  4103.177  ,  1417.3341 ,  3481.5896 ,  2712.7612 ,
        3279.2583 ,  2916.1855 ,  2704.0698 ,  3886.776  ,  4331.296  ,
        5705.576  ,  5051.7114 ,  1866.8605 ,  4945.733  ,  2443.564  ,
        3665.2422 ,  3609.143  ,  7308.669  ,  1724.7394 ,  2348.53   ,
        2257.9622 ,  8096.5767 ,  2209.3018 ,  2437.376  ,  2203.121  ,
        4450.839  ,   666.5943 ,  3997.0264 ,  4556.8403 ,  1265.7389 ,
        2588.0044 ,  8333.976  ,  2349.1104 ,  1185.5015 ,  2954.09   ,
        5488.135  ,  6129.9424 ,  7556.636  ,  2504.3965 ,  1215.2905 ,
        1569.6326 ,  2012.1278 ,  3055.8882 ,  1564.7899 ,  1556.4565 ,
        3194.9714 ,  8172.142  ,  3020.503  ,  4302.701  , 15165.77   ,
        9011.595  ,  3528.7068 ,  1770.8306 ,  1608.0128 ,   576.90686,
        5006.4443 ,  8421.377  ,  2800.565  ,  6767.6187 ,  2217.4224 ,
        1328.0511 ,  3635.2747 ,  1414.9724 , 12152.773  ,  1322.6082 ,
        4783.2095 ,  1153.5709 ,  7149.4937 ,  2786.9875 ,  8834.853  ,
        1541.5691 ,  4142.6733 ,  2471.6655 ,   446.61185,  1282.5778 ,
         857.1893 ,  1368.8923 ,  2784.0166 ,  1923.8629 ,  2567.7336 ,
        1846.0009 ,  1832.0024 ,  1336.1622 , 10963.532  ,   861.2018 ,
        3280.0454 ,  2608.4885 , 17783.014  ,  2552.256  ,  1671.2167 ,
        1674.3804 ,  3966.4402 ,  1580.963  ,  5992.351  ,  1390.6105 ,
        3411.0256 ,  4460.9634 ,  8695.245  ,  2099.3555 , 17271.96   ,
        1384.2289 ,  2529.8337 ,  1047.599  ,  3728.2195 ,  2974.2588 ,
        2616.6729 ,  2566.7583 ,  1030.8806 ,  1582.8773 ,  1817.6243 ,
        2907.7766 ,  1911.9403 ,  2298.3132 ,  2592.7705 ,  7487.61   ,
        1922.5968 ,  2013.2506 ,  1692.9385 ,  5210.144  ,  1205.4312 ,
        1270.7144 ,  1824.9148 ,   806.11505,  2807.6177 ,  3598.6638 ,
        2525.448  ,  1489.0448 ,  2089.9285 ,  2852.0908 ,  1400.4197 ,
        1939.6354 ,  2274.001  ,  7089.1987 ,  3895.7544 ,  5331.8335 ,
         899.38635,  3699.1418 ,  2058.4229 ,  2836.4321 ,  1864.9434 ,
        2854.628  ,  2090.9822 ,  1793.2305 ,  2111.4438 ,  6234.137  ,
        1823.6875 ,  2279.0227 ,  1670.6724 ,  3211.6128 ,  2477.4197 ,
        2405.348  ,  1266.0426 ,  4737.2544 ,  2323.2693 ,  2435.7397 ,
        1241.0034 ,  2623.607  ,  2383.2444 ,  1949.8322 ,  1947.5791 ,
        2722.4895 ,  4005.5188 ,  2041.3424 ,  7031.6226 ,  2182.536  ,
        1249.0525 ,  5370.845  ,  2875.5598 ], dtype=float32)

In [68]:
data_train_categorical_levels = data_train.select_dtypes(include = "object").values.tolist()
data_train_categorical_levels = set(data_train_categorical_levels)
data_train_categorical_levels

TypeError: unhashable type: 'list'